# Generated by Django 2.2.14 on 2020-07-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_tmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmp',
        ),
    ]
